"""organisations and room and object

Revision ID: b4da09fbdf7e
Revises: af3b3a98d193
Create Date: 2020-05-19 10:57:24.053232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4da09fbdf7e'
down_revision = 'af3b3a98d193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('organisation', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('lend_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lend_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organisation'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_object_article'), 'inventory_object', ['article'], unique=False)
    op.create_index(op.f('ix_inventory_object_description'), 'inventory_object', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_object_description'), table_name='inventory_object')
    op.drop_index(op.f('ix_inventory_object_article'), table_name='inventory_object')
    op.drop_table('inventory_object')
    # ### end Alembic commands ###
