"""inventoryobjects table

Revision ID: eb83a82b3601
Revises: af3b3a98d193
Create Date: 2020-05-16 16:22:15.218500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb83a82b3601'
down_revision = 'af3b3a98d193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('organisation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_object_article'), 'inventory_object', ['article'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_object_article'), table_name='inventory_object')
    op.drop_table('inventory_object')
    # ### end Alembic commands ###
